version: "2"

services:
  db:
    container_name: dss2022-postgres
    image: postgres:12
    ports:
      - 25432:5432
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=welcome
      - POSTGRES_USER=admin
      - POSTGRES_DB=dss2022
    volumes:
      - ./.datadir:/var/lib/postgresql/data
