version: "2"

services:
  db:
    container_name: dss2022-mysql
    image: mysql:latest
    restart: always
    ports:
      - 25432:5432
    environment:
      - LC_ALL=C.UTF-8
      - MYSQL_DATABASE=DSS2022
      - POSTGRES_PASSWORD=dss2022
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=dss2022
    volumes:
      - './mysql_data:/var/lib/mysql'